### ISSUE TITLE
how to query previous dates to present

### ISSUE THREAD

**Issue by lawrence19** [edgedalmacio/phisix#10]
hi sir, is it possible to query based on date range and having its output as CSV file. I will use it for my excel macro program?

thanks!

**Comment by edgedalmacio** [comment]
I like this suggestion. I'll mark it down as an enhancement for now.

While this functionality is not yet available, you'll have to make multiple API calls at the moment. 

Samples:

XML
http://phisix-api.appspot.com/stocks/TEL.2015-01-19.xml
http://phisix-api.appspot.com/stocks/TEL.2015-01-20.xml
http://phisix-api.appspot.com/stocks/TEL.2015-01-21.xml

JSON
http://phisix-api.appspot.com/stocks/TEL.2015-01-19.json
http://phisix-api.appspot.com/stocks/TEL.2015-01-20.json
http://phisix-api.appspot.com/stocks/TEL.2015-01-21.json

Format: 
/stocks/{symbol}.{yyyy-MM-dd}.{json|xml}

**Comment by lawrence19** [comment]
hi sir, thanks for your help and acknowledging my suggestion.
I am currently using your work in my excel macro program in monitoring daily stock quotes.
I used other website to grab historical data, but i prefer using your API since i always get the lastest and  up to date data which is very critical on my stock analysis.
BTW I am currently I'm using this url:

http://openpse.com/api/quotes/?from_date=2014-08-29&to_date=2014-11-14&format=csv

Is it possible to do as such, wherein the resulting query provides single .csv file for all stocks. My existing program runs on the result of this query.

thank you so much.

**Comment by racosuco** [comment]
Hi, is this suggestion implemented right now? Or we still have to make multiple API calls? Thank you
