### ISSUE TITLE
Real time will be much better if  it has OPEN - HIGH - LOW data feed

### ISSUE THREAD

**Issue by rence19** [edgedalmacio/phisix#12]
Hi Sir,

Is it possible to include such data?

Thanks

**Comment by edgedalmacio** [comment]
Let me see what I can do.

**Comment by jhunexjun** [comment]
Yeah this is what I wanna get too.

**Comment by leoclintag** [comment]
hi sir edge,  im very much interested in using your api,  how would i be able to get the open high low close prices?  thank you and hoping for your answer,  leoclintag@gmail.com

**Comment by dirkargyle** [comment]
Hey can you share how to access open high low close data?
