### ISSUE TITLE
API not accessible anymore on some devices

### ISSUE THREAD

**Issue by ajcordenete** [edgedalmacio/phisix#128]
Hi Edge,

I noticed that just recently, some of my android devices have been having a problem accessing the API. It's working fine on other devices while some are getting an error "This site can't be reached". All are working fine previously. I'm not sure if a simple server restart would fix the issue but I think it's worth a try. Thank you so much!

**Comment by edgedalmacio** [comment]
Which endpoint are you using?

You can also check the status here: 
https://statuspage.freshping.io/29889-phisixapi

**Comment by ajcordenete** [comment]
i'm using this endpoint:
https://phisix-api.appspot.com/stocks.json

The endpoint is loading fine on my laptop's web browser as well on my 2 other mobile devices. But somehow, other devices could not load the same exact endpoint.  Any ideas?

![device1](https://user-images.githubusercontent.com/61613338/94019653-9b69e280-fde4-11ea-96eb-e6d64f73e7a8.png)
![device2](https://user-images.githubusercontent.com/61613338/94019661-9d33a600-fde4-11ea-946d-3b030abd6845.png)
![device3](https://user-images.githubusercontent.com/61613338/94019668-9dcc3c80-fde4-11ea-833a-0efb69b5f088.jpg)

**Comment by edgedalmacio** [comment]
`DNS_PROBE_FINISHED_NXDOMAIN` seems like a network issue to me. The problem could either be on the device or the network you're connected to.

**Comment by ajcordenete** [comment]
Yup, I agree. The errors shown are the same as when having a network connectivity issue. But rest assured that the internet on the device is working. tried it on both wifi and mobile data but still could not load the endpoint on those devices :(
