### ISSUE TITLE
http://phisix-api.appspot.com/stocks.xml is Over Quota ***CRITICAL***

### ISSUE THREAD

**Issue by heyou93** [edgedalmacio/phisix#14]
There are times that when i opened and access this page (http://phisix-api.appspot.com/stocks.xml) and other related pages (either JSON OR XML) it shows  the following:

Over Quota

This application is temporarily over its serving quota. Please try again later.

![image](https://cloud.githubusercontent.com/assets/8090574/6817516/7a5f04e6-d2dc-11e4-9c9c-f626aa01abda.png)

Please kindly fix it.

**Comment by edgedalmacio** [comment]
Try http://phisix-api2.appspot.com/stocks.xml <http://phisix-api2.appspot.com/stocks.xml>

-
Edge Dalmacio

**Comment by edgedalmacio** [comment]
I've setup a load balancer between phisix-api and phisix-api2. That should help fix the "Over Quota" issue.
