### ISSUE TITLE
Not getting any result for a given stock/date request

### ISSUE THREAD

**Issue by jerarl** [edgedalmacio/phisix#15]
I'm not getting any result from this request on dates March 31, 2015 onwards
GET http://phisix-api.appspot.com/stocks/{symbol}.{yyyy-MM-dd}.{json|xml}

With result
http://1.phisix-api.appspot.com/stocks/MEG.2015-03-30.json

Without result
http://1.phisix-api.appspot.com/stocks/MEG.2015-03-31.json
http://1.phisix-api.appspot.com/stocks/MEG.2015-04-15.json
http://1.phisix-api.appspot.com/stocks/MEG.2015-05-15.json
http://1.phisix-api.appspot.com/stocks/MEG.2015-10-26.json

**Comment by kenjhim** [comment]
Me too. Can't see any content for 2016. 
http://1.phisix-api.appspot.com/stocks/BDO.2016-01-19.json

**Comment by edgedalmacio** [comment]
FIXED: cron was disabled. you'll start seeing history starting from 2016-03-23

sample:
http://phisix-api.appspot.com/stocks/BDO.2016-03-23.json

i'll put in a job to back track lost history from 2016, and if possible 2015.

**Comment by raybuensuceso** [comment]
this issue persists again
