### ISSUE TITLE
PSEi

### ISSUE THREAD

**Issue by ghost** [edgedalmacio/phisix#22]
There are 2 PSE symbol.  cannot get PSEi price using http://phisix-api3.appspot.com/stocks/PSE.json

**Comment by edgedalmacio** [comment]
I think you're looking for "All Shares"

http://phisix-api3.appspot.com/stocks/ALL.json

Should I map "ALL" to "PSEI"?

**Comment by jasperdlcruz** [comment]
Look here. http://edge.pse.com.ph/ scroll down and look for index summary. there is psei and all shares.

**Comment by jasperdlcruz** [comment]
To shorten this. Can you add I to PSE(name) before ALL for it to become PSEI(symbol) because now there are 2 PSE (symbol)

**Comment by jasperdlcruz** [comment]
Another thing is the wrong price and labeling. http://phisix-api3.appspot.com/stocks/ALL.json. "ALL" Price now is 4386.80 but only displays 438. Labeling can you refer to this http://edge.pse.com.ph/ and look for index summary. you're displaying Change in "amount", percent change is correct. in "volume" you are displaying the amount.
