### ISSUE TITLE
can't retrieve data

### ISSUE THREAD

**Issue by darylfabregas** [edgedalmacio/phisix#23]
Hi,

I use excel to monitor the market price by importing the xml data to excel but as I notice since yesterday (feb. 27, 2017), excel cannot retrieve the data from the source. As i visit the page through a web browser it says page not available.

**Comment by byrnecode** [comment]
Yes, same here.. I can't retrieve json data. I think there's an issue with their server.. hopefully it get fixed soon because my personal trading app is depending on this API.. :(

**Comment by edgedalmacio** [comment]
Ok, lemme take a look. Apologies for the inconvenience.

**Comment by bzarzuela** [comment]
I'm using it as well for a personal trading app. :)

**Comment by edgedalmacio** [comment]
Fixed. See c821621 for details.

**Comment by byrnecode** [comment]
Thanks sir!

**Comment by darylfabregas** [comment]
fixed! thanks :)
