### ISSUE TITLE
BUG: Some endpoints dont work due to missing header

### ISSUE THREAD

**Issue by hack-of-all-codes** [edgedalmacio/phisix#24]
Breaking Tests:
```
PseClientTest
.findSecurityOrCompany
.companyInfo
.companyInfoHistoricalData
```

Issue with missing header "referrer".

Too lazy to fix this myself. Just giving you a heads up

**Comment by edgedalmacio** [comment]
The latest [build](https://travis-ci.org/edgedalmacio/phisix) seems to be working just fine.

Please make sure you have the latest copy of the code.

You can also try running `mvn test` and see if that works for you.
