### ISSUE TITLE
Missing com.googlecode.phisix.api.model.Stocks

### ISSUE THREAD

**Issue by abcdefgh12345678** [edgedalmacio/phisix#26]
On downloading the code, when opened in Intellij IDEA CE, the com.googlecode.phisix.api.model.Stocks package could not be found in src and thus the import statement for the same gave errors.
<img width="360" alt="screen shot 2017-04-15 at 9 39 37 pm" src="https://cloud.githubusercontent.com/assets/25474269/25064990/131ab926-2224-11e7-9287-ffc3fba55aed.png">

**Comment by edgedalmacio** [comment]
`com.googlecode.phisix.api.model.Stocks` class is generated during the `generate-sources` phase of maven. Run `mvn generate-sources` and look at your `target` folder to see what I'm talking about.
