### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

### ISSUE THREAD

**Issue by Natski** [edgedalmacio/phisix#33]
hi, I'am getting a problem in the api, it says "Failed to load http://phisix-api4.appspot.com/stocks/BDO.json". What ways can I do to not commit in this problem? Sorry I'am just beginning to learn to fetch an api. Thank you in advance.

**Comment by edgedalmacio** [comment]
Duplicate of #9
