### ISSUE TITLE
Is there a real time api?

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [edgedalmacio/phisix#36]
So far all I see are JSON/XML feeds which I assume are not real time.

**Comment by boknoypatotoy** [comment]
For the realtime data feeds ... you need to apply to PSE and pay monthly for it (which is expensive)... and before they'll grant you your request ... you need to be a licensed broker ... In case you are granted connections for whatever reason ... you need to follow their very strict  documentation ... or they will revoke your access ...

This phisix free API ... for your information ... is a scrape on PSE website ... if you do it on your own .. you are required to have a proper authentication in which the author have established a long time ago .. if I'm not mistaken ... And the frequency set by PSE for public consumption is every minute.

This is all we can have for a free service ...
