### ISSUE TITLE
Date function

### ISSUE THREAD

**Issue by raybuensuceso** [edgedalmacio/phisix#40]
GET /stocks/{symbol}.{yyyy-MM-dd}.{json|xml} is not working anymore? Request returns 404 when there is date input

**Comment by edgedalmacio** [comment]
What stock and date are you trying to access?

**Comment by treboj** [comment]
Hi @edgedalmacio,
You can try the endpoints to see the 404 error:
http://phisix-api2.appspot.com/stocks/2GO.2019-09-15.json
http://phisix-api2.appspot.com/stocks/BDO.2019-09-15.json

**Comment by edgedalmacio** [comment]
2019-09-15 is a Sunday. There's no trading that day. That's why you're
getting a 404 Not Found response.

**Comment by treboj** [comment]
Hi @edgedalmacio,

Thanks you! I missed that. We have to remove the weekdays and holidays on our api request.
