### ISSUE TITLE
Issue with decimal places.

### ISSUE THREAD

**Issue by heyou93** [edgedalmacio/phisix#8]
Stock prices that has more than 2 decimal places are inaccurate when using this API it rounded-off to 2 decimal places. Example: EG, AR, GREEN, and etc. Please increase the decimal places upto 4 thanks!

**Comment by edgedalmacio** [comment]
Hi, sorry for not getting back to you sooner.

This is an issue from the raw PSEi feed, notice the ``lastTradedPrice`` below:

    { "indicator" : "N",
      "indicatorImg" : "",
      "lastTradedPrice" : "0.02",
      "percChangeClose" : "0",
      "securityAlias" : "E-Games",
      "securitySymbol" : "EG",
      "totalVolume" : "51,200,000"
    }

This is a similar issue to https://github.com/edgedalmacio/phisix/issues/4
