### ISSUE TITLE
CORS is disabled

### ISSUE THREAD

**Issue by aaroncajes** [edgedalmacio/phisix#9]
I'm using jQuery's AJAX to access the API but i get an error message from the server that the CORS is disabled. Would be nice if it's enabled. :)

**Comment by froilan** [comment]
Hi, had this issue as well. 
Just wondering if it's possible to enable CORS?

**Comment by emanlodovice** [comment]
Thanks for the wonderful api. Just bumping this issue again since I just had this issue. 

Here is the error I get in the browser
```
Access to XMLHttpRequest at 'http://phisix-api.appspot.com/stocks/MM.2020-07-15.json' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by emanlodovice** [comment]
Thanks for fixing the issue. I can see that the CORS header is now present in some response but there are also some responses without it. I am not sure why. It could have something to do with new nodes spawned by GCP's auto scaling.

![2020-07-26_13:24:37](https://user-images.githubusercontent.com/3273867/88472305-efbb2800-cf43-11ea-889c-d809fb215310.png)
![2020-07-26_13:26:45](https://user-images.githubusercontent.com/3273867/88472306-f0ec5500-cf43-11ea-9f7a-8ca440930c06.png)
