### ISSUE TITLE
2 PSE symbols

### ISSUE THREAD

**Issue by boknoypatotoy** [edgedalmacio/phisix#90]
Although I've already coded the work around ... but still ... it is best to tell you that the symbol for PSE and PSEi are the same ....

Request to change PSE index symbol to PSEi ... so that it will not conflict with the other PSE ...

**Comment by boknoypatotoy** [comment]
this is related to https://github.com/edgedalmacio/phisix/issues/22
i'm closing this

**Comment by edgedalmacio** [comment]
Duplicate of #22
